### ISSUE TITLE
【.orgに上がってない】プラグイン一覧画面で表示されるプラグインアイコンを作る

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-link-target-controller#37]

**Comment by sysbird** [comment]
@kurudrive 

アイコン候補です
(左) VKカラー
(右)↑が少しキツイので　VK Blocksのアイコンの配色
このアイコンを置くフォルダ /assets はgiithub 管理でない(?)ので、Subversion  でアップするんでしょうかね？

![icon](https://user-images.githubusercontent.com/4631838/133762779-1d43fe1c-daeb-4533-a520-487fcc2e92ac.jpg)

**Comment by goutetsuguma** [comment]
@sysbird 
とりさんありがとうございます!! （作成いただいてから数ヶ月たってしまいましたね、、、すみません、、！）
VKマークがついていなかったのでVKマークを付けたバージョンの作成と、色の件はデザインの共通化をしていこうということで、VKカラーの方（左側）でお願いいたしますmm

色やVKマークの配置はVK Filter Searchのアイコンを参考にお願いいたしますmm

▼参考VK Filter Search
https://ja.wordpress.org/plugins/vk-filter-search/

**Comment by sysbird** [comment]
@goutetsuguma 
https://www.figma.com/file/ChMacAIaBTmbE3yNW1xVJS/vk-filter-search
ここの一番下に追加しました！
VKマークつけるのに、矢印を少しシュッとさせて重ならないようにしました

![icon](https://user-images.githubusercontent.com/4631838/143541903-86aa30f8-f441-4443-87d1-6333a17ea9f2.jpg)
した

**Comment by goutetsuguma** [comment]
@sysbird @kurudrive 
とりさんありがとうございます！矢印もしゅっとして良くなりました！

一点、デザインの共通化というところで、黒色の四角の部分の線をもう少し細くする（Filter Serch のフィルターアイコンの線くらいの細さ）といいのかなと思いましたmm　

@kurudrive 
ロゴとかバナーはいりますかねぇ。。？
わたし個人的には、バナーとロゴがあるとvektorの製品紹介ページに載せれるので欲しいなと感じました。

**Comment by sysbird** [comment]
@goutetsuguma 
ありがとうございます〜たしかに！
調整します

ロゴ、バナーも VK Filter Search をもとに作成するかんじでしょうかね

**Comment by sysbird** [comment]
@goutetsuguma 
とりいそぎアイコンのみ更新しました！

**Comment by goutetsuguma** [comment]
@kurudrive @sysbird 
とりさんありがとうございます！以下の微調整をお願いいたします。

![vk-link-target-controller](https://user-images.githubusercontent.com/5525368/143829869-7d4f9ac8-1fba-401e-92a2-91fd612f576a.png)

石川さんも、ちらっとご確認をお願いいたしますｍｍ
▼Figmaのデータ
https://www.figma.com/file/ChMacAIaBTmbE3yNW1xVJS/vk-filter-search

---
## ロゴとバナーについて
>ロゴ、バナーも VK Filter Search をもとに作成するかんじでしょうかね

→はい、そんな感じでおねがいいたしますmm 
お手隙の際にすすめていただけるとうれしいですーmm

**Comment by sysbird** [comment]
あぁ〜あとから四角だけ小さくしたときにずれてしまった…調整します！

**Comment by sysbird** [comment]
@goutetsuguma @kurudrive 
figmaを更新しました
アイコン調整して、まず小さいバナーを追加

文言が適当ですので、正しいものをもらえますか  >  石川さん
・キャッチフレーズ(1行で2、3語)英語/日本語
・ちょっとした説明(2行ほど)英語/日本語
適当でよければ、プラグインのページから引用します

![ vk-link](https://user-images.githubusercontent.com/4631838/143969791-5d05676c-d3b0-409c-a83b-8b9c86e0328e.png)

**Comment by kurudrive** [comment]
Redirect で

**Comment by kurudrive** [comment]
@sysbird @drill-lancer 

どうも10upのスクリプトで現状svnに上がってないっぽくて反映されてない状態なので、反映されるように調査よろしくお願いいたします。

https://plugins.svn.wordpress.org/vk-link-target-controller/assets/

https://wordpress.org/plugins/vk-link-target-controller/

**Comment by drill-lancer** [comment]
.wordpress-org のディレクトリ名が若干おかしかったようでそこを修正したら反映されるようになりました。
https://wordpress.org/plugins/vk-link-target-controller/

**Comment by kurudrive** [comment]
@drill-lancer お！反映されましたね！ありがとうございます！

**Comment by sysbird** [comment]
@drill-lancer @kurudrive 
申しわけありません
対応ありがとうございます！
