### ISSUE TITLE
デフォルトで各投稿タイプ有効化状態にしておく

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-link-target-controller#53]
現状 : 設定画面に移動して、機能をアクティブにする投稿タイプにチェックを入れないと動作しない
変更後 : プラグインを有効化したら全投稿タイプで使えるようになっている。設定画面で、表示しない投稿タイプはチェックを外すようにする。

- [ ] 既存ユーザーの設定に影響を及ぼさないように PHPUnitテストをちゃんと書いて確認する。

**Comment by drill-lancer** [comment]
マージされたので Close
