### ISSUE TITLE
PHP 8 環境下で、a要素が空になるケースが発生

### ISSUE THREAD

**Issue by mypacecreator** [vektor-inc/vk-link-target-controller#62]
PHPバージョンを8.0, 8.1系にした際に、リンク先指定を行った投稿以降のa要素がうまく出力されない現象が発生しています。

ただし、テーマによって発生条件が異なるようです。

## この現象が発生したテーマの例
- Twenty Thirteen より前のデフォルトテーマ
- 自作テーマ（PHP7までは正常動作を確認済み）
- Nishiki （公式ディレクトリ登録テーマ）
- Snow Monkey
- SWELL

## この現象が発生しなかったテーマの例
- Twenty Fourteen 以降のデフォルトテーマ
- Ligntning 
- yStandard

他の公式ディレクトリテーマでも再現するものとしないものがあるようでした。
個別の他社テーマでの挙動まで調べていただく必要はないと思いますが、Twenty Thirteen 以前とTwenty Fourteen 以降の違いが謎で...。
発生するテーマとそうでないテーマの違いが突き止められず、対応に窮したので情報共有しました。

なお、この現象が発生しない場合でも、PHP8ではもとの投稿のパーマリンクが出力され、クリックすると302リダイレクトで指定したURLに飛ぶ、という挙動の違いがあります。これは開発側で意図した挙動でしょうか？

**Comment by aonoto** [comment]
横から失礼します。私も似た症状が起きたので、調べてみました。
推測ですが、rewrite_link()の引数と、[apply_filter('the_permalink')が期待するフック関数の引数](https://developer.wordpress.org/reference/hooks/the_permalink/)が一致していない(+PHP8以降の比較結果の違い)のが原因ではと思われ、現状の仕様に沿ったフック関数にするコンセプト的なパッチを作成しました。
WordPress 6.1.1とPHP-8.1.14/7.4.33(ただしCentOS7用Remiのパッケージ)で動作していることは確認しました(Works for meレベルですが)。よろしければ参考にしてください。
[the_permalink-20230123.patch](https://github.com/vektor-inc/vk-link-target-controller/files/10517693/the_permalink-20230123.patch)

**Comment by MarikoMorimoto** [comment]
横から失礼します。
私の環境でも、当該プラグインでリンクを設定した際、a要素が空になるケースが発生しています。
@mypacecreator さんがissue を立ててくださっているおかげで、他の環境でも再現していることが確認できて助かりました。ありがとうございます。

---

WordPress 6.3.2 
PHP 8.0系
独自テーマ

**Comment by kurudrive** [comment]
あぁぁぁ...すみません...見落としておりました。
今更で恐れ入りますが近日中に修正いたします (´；ω；｀)

**Comment by kurudrive** [comment]
@mypacecreator @aonoto @MarikoMorimoto 
今更でウルトラ恐縮でございます！
修正版 1.7.4.2 アップいたしました！ (´；ω；｀)
